
import React from 'react';
import { PaperCard } from './components/PaperCard';
import { Section } from './components/Section';
import { ReadingPathCard } from './components/ReadingPathCard';
import { PAPERS, READING_PATHS, REFERENCES } from './constants';

const App: React.FC = () => {
  return (
    <div className="min-h-screen bg-slate-900 font-sans">
      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 sm:py-16">
        <header className="text-center mb-12">
          <h1 className="text-4xl sm:text-5xl font-extrabold text-white leading-tight">
            A Curated List of 10 Essential LLM Papers
          </h1>
          <p className="mt-4 max-w-2xl mx-auto text-lg text-slate-400">
            Covering theory, alignment, reasoning, and applications to build a systematic understanding and research perspective.
          </p>
        </header>

        <Section title="The Core Reading List">
          <div className="space-y-6">
            {PAPERS.map((paper) => (
              <PaperCard key={paper.id} paper={paper} />
            ))}
          </div>
        </Section>
        
        <Section title="Learning & Research Paths">
           <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
              {READING_PATHS.map(path => (
                  <ReadingPathCard key={path.title} path={path} papers={PAPERS} />
              ))}
           </div>
        </Section>
        
        <Section title="Extension Directions">
            <div className="bg-slate-800/50 p-6 rounded-lg border border-slate-700 space-y-4 text-slate-300">
                <p>
                    <strong>Expand to New Domains:</strong> To explore multimodality, programming capabilities, or dialogue systems, build upon this core list with relevant survey papers and recent work, while maintaining a firm grasp of the fundamental principles.
                </p>
                <p>
                    <strong>Deeper Analysis:</strong> For summaries, experimental designs, and reproducibility assessments of each paper, a more granular reading plan and note-taking template can be customized to your specific research interests.
                </p>
            </div>
        </Section>

        <Section title="References">
            <div className="bg-slate-800/50 p-6 rounded-lg border border-slate-700">
                <ul className="grid grid-cols-1 sm:grid-cols-2 gap-x-8 gap-y-3">
                    {REFERENCES.map(ref => (
                        <li key={ref.title}>
                            <a 
                                href={ref.url} 
                                target="_blank" 
                                rel="noopener noreferrer" 
                                className="text-sky-400 hover:text-sky-300 hover:underline transition-colors duration-200"
                            >
                                {ref.title}
                            </a>
                        </li>
                    ))}
                </ul>
            </div>
        </Section>

      </main>
      <footer className="text-center py-6 text-slate-500 text-sm">
          <p>Generated by a world-class senior frontend React engineer.</p>
      </footer>
    </div>
  );
};

export default App;
